# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format

format = """\
[â•­â•´](238)$env_var\
$all[â•°â”€](238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[ï•“](bold green)"
error_symbol = "[ï•“](238)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true  # disable in powershell
show_always = false

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
home_symbol = "â›º ~ âš¡"
read_only_style = "red"
read_only = " ğŸ”’ "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "î‚  "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "â€¦/"
style = "bold purple"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³- âš”ï¸"
up_to_date = "ï† "
untracked = "ğŸ›¤ï¸ "
ahead = "â‡¡${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨Ã—${ahead_count}ğŸ¢ Ã—${behind_count}"
behind = "â‡£${count}"
stashed = "ğŸ“› "
modified = "ğŸ“ "
staged = '[++\($count\)](green)'
renamed = "ğŸ—ƒï¸ "
deleted = "ğŸ—‘ï¸ "

[terraform]
format = "via [ï„µ - â˜£ï¸â˜£ï¸â˜£ï¸ terraform $version]($style) ï¥‚ [$workspace]($style) "

[vagrant]
format = "via [ï„µ vagrant $version]($style) "

[gcloud]
symbol = "ğŸ‡¬- ğŸ¦– "
[gcloud.region_aliases]
us-central1 = "uc1"
asia-northeast1 = "an1"
format = "[$symbol$active]($style) "
style = "bold yellow"

[sudo]
style = "bold green"
symbol = "ğŸ‘‘-ğŸ‘©â€ğŸ’» "
disabled = false

[docker_context]
format = "via [ïŒˆ ğŸ³ $context](bold blue) "

[helm]
format = "via [â˜¸ï¸  $version](bold purple) "

[azure]
disabled = false
format = "on [$symbol($subscription)]($style) "
symbol = "ï´ƒ - ğŸ¦œ "
style = "purple cyan"

[pulumi]
symbol = "ğŸ“¦"
format = "[$symbol ($username@)$stack](bold 164) "

[python]
symbol = "ï Ÿ - ğŸ"
python_binary = "python3"

[golang]
format = "via [ğŸğŸ‘…$version](bold cyan) "

[nodejs]
format = "via [ï¢˜-ğŸ”· $version](bold green) "
disabled = true

[ruby]
format = "via [ğŸ¦€ $version]($style) "

[kubernetes]
format = 'on [â˜¸ï¸  $context\($namespace\)](bold purple) '
disabled = false
[kubernetes.context_aliases]
"lke82288-ctx" = "l-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"
